Repository X3NOSIZ/exploitHacktober, pull requests merged in 2022-10, with the labels that each got.

#1 added LICENSE — 💀
  LICENSE
Labels: documentation, enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest22

#3 CORSProxy Wrapper
  injectOmegle.js
Labels: enhancement, help wanted, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#4 It works now :pizza:
  injectOmegle.js
Labels: bug, enhancement, help wanted, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#5 ______init______
  showFps.js
Labels: enhancement, hacktoberfest-accepted

#6 createOverlay();
  showFps.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7 __update1.0.2
  showFps.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#8 fix bug
  showFps.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
